### ISSUE TITLE
add forgot password option

### ISSUE THREAD

**Issue by josiahcoad** [elishacoad/cosmos#5]

**Comment by josiahcoad** [comment]
use: https://aws-amplify.github.io/docs/js/authentication#forgot-password
and for reference: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html

**Comment by elishacoad** [comment]
A more direct resource: https://serverless-stack.com/chapters/handle-forgot-and-reset-password.html
